NAME: "Ruslan"
SURNAME: "Gimaev"
METHOD_NAME: "name"
INTERFACE_METHOD_NAME: "invoke"
BENCHMARK_CLASS_NAME: "MethodAccessBenchmark"
THREADS_COUNT: 1
FORKS_COUNT: 3
WARMUP_FORKS_COUNT: 1
WARMUP_ITERATIONS: 5
WARMUP_TIME: 5
MEASUREMENT_ITERATIONS: 10
MEASUREMENT_TIME: 5
SHOULD_FAIL_ON_ERROR: true
SHOULD_DO_GC: true
