BENCHMARK_CLASS_NAME: "MethodAccessBenchmark"
METHOD_NAME: "name"
THREADS_COUNT: 1
FORKS_COUNT: 1
WARMUP_FORKS_COUNT: 1
WARMUP_ITERATIONS: 3
WARMUP_TIME: 5
MEASUREMENT_ITERATIONS: 3
MEASUREMENT_TIME: 5
